# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-21 10:00
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('image', pyuploadcare.dj.models.ImageField(blank=True)),
                ('contact', models.IntegerField(null=True)),
                ('description', models.TextField(max_length=10000)),
                ('category', models.CharField(choices=[('Restaurants ', 'restaurants'), ('Bars', 'bars'), ('Bookshop', 'bookshop'), ('Construction Material Hardware', 'construction material hardware'), ('Electric Hardware', 'electric hardware'), ('Botique', 'botique'), ('Foods', 'foods'), ('Hospitals', 'hospitals'), ('Supermarkets', 'supermarkets')], max_length=1000)),
                ('verified', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', pyuploadcare.dj.models.ImageField(blank=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('contact', models.IntegerField(null=True)),
                ('description', models.TextField(max_length=10000)),
                ('category', models.CharField(choices=[('Flats and Apartments', 'flats and apartments'), ('Bedsitters', 'bedsitters'), ('Houses', 'houses'), ('Studio ', 'studio'), ('Rooms', 'rooms'), ('Town Houses', 'town houses'), ('Bungalows', 'bungalows'), ('Single Rooms', 'single rooms'), ('Hostels', 'hostels')], max_length=1000)),
                ('verified', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', pyuploadcare.dj.models.ImageField(blank=True)),
                ('bio', models.CharField(default='Hi!', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('image', pyuploadcare.dj.models.ImageField(blank=True)),
                ('category', models.CharField(choices=[('Water point', 'water point'), ('Massage', 'massage'), ('Phone repair', 'phone repair'), ('Library', 'library'), ('Shoe repair', 'shoe repair'), ('Spa', 'spa'), ('Kibanda foods', 'kibanda foods'), ('Barber', 'barber'), ('Saloon', 'saloon')], max_length=1000)),
                ('price', models.IntegerField(null=True)),
                ('description', models.TextField(max_length=10000)),
                ('contact', models.IntegerField(null=True)),
                ('available', models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], max_length=1000)),
                ('verified', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('useremail', models.CharField(max_length=140)),
                ('userpassword', models.CharField(max_length=100)),
                ('last_login', models.DateField(auto_now=True)),
                ('profilepic', pyuploadcare.dj.models.ImageField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='life.User'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='life.User'),
        ),
    ]
