# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-21 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='bsn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='life.Business'),
        ),
        migrations.AddField(
            model_name='comments',
            name='comment',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='hsng',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='life.Housing'),
        ),
        migrations.AddField(
            model_name='comments',
            name='svc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='life.Services'),
        ),
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.CharField(choices=[('Restaurants ', 'restaurants'), ('Hospitals', 'hospitals'), ('Bookshop', 'bookshop'), ('Supermarkets', 'supermarkets'), ('Construction Material Hardware', 'construction material hardware'), ('Foods', 'foods'), ('Bars', 'bars'), ('Electric Hardware', 'electric hardware'), ('Botique', 'botique')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='life.User'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='category',
            field=models.CharField(choices=[('Studio ', 'studio'), ('Rooms', 'rooms'), ('Single Rooms', 'single rooms'), ('Bedsitters', 'bedsitters'), ('Hostels', 'hostels'), ('Town Houses', 'town houses'), ('Flats and Apartments', 'flats and apartments'), ('Houses', 'houses'), ('Bungalows', 'bungalows')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='services',
            name='category',
            field=models.CharField(choices=[('Barber', 'barber'), ('Water point', 'water point'), ('Spa', 'spa'), ('Library', 'library'), ('Saloon', 'saloon'), ('Phone repair', 'phone repair'), ('Shoe repair', 'shoe repair'), ('Kibanda foods', 'kibanda foods'), ('Massage', 'massage')], max_length=1000),
        ),
    ]
