# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-22 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0002_auto_20190822_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.CharField(choices=[('Foods', 'foods'), ('Bookshop', 'bookshop'), ('Supermarkets', 'supermarkets'), ('Electric Hardware', 'electric hardware'), ('Bars', 'bars'), ('Construction Material Hardware', 'construction material hardware'), ('Hospitals', 'hospitals'), ('Botique', 'botique'), ('Restaurants ', 'restaurants')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='housing',
            name='category',
            field=models.CharField(choices=[('Bungalows', 'bungalows'), ('Hostels', 'hostels'), ('Bedsitters', 'bedsitters'), ('Town Houses', 'town houses'), ('Single Rooms', 'single rooms'), ('Rooms', 'rooms'), ('Houses', 'houses'), ('Flats and Apartments', 'flats and apartments'), ('Studio ', 'studio')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='services',
            name='available',
            field=models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='services',
            name='category',
            field=models.CharField(choices=[('Kibanda foods', 'kibanda foods'), ('Spa', 'spa'), ('Water point', 'water point'), ('Saloon', 'saloon'), ('Library', 'library'), ('Shoe repair', 'shoe repair'), ('Massage', 'massage'), ('Phone repair', 'phone repair'), ('Barber', 'barber')], max_length=1000),
        ),
    ]
