# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-22 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0003_auto_20190822_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profilepic',
        ),
        migrations.AddField(
            model_name='comments',
            name='bsn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='life.Business'),
        ),
        migrations.AddField(
            model_name='comments',
            name='comment',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='hsng',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='life.Housing'),
        ),
        migrations.AddField(
            model_name='comments',
            name='svc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='life.Services'),
        ),
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.CharField(choices=[('Construction Material Hardware', 'construction material hardware'), ('Electric Hardware', 'electric hardware'), ('Foods', 'foods'), ('Hospitals', 'hospitals'), ('Restaurants ', 'restaurants'), ('Botique', 'botique'), ('Supermarkets', 'supermarkets'), ('Bars', 'bars'), ('Bookshop', 'bookshop')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='life.User'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='category',
            field=models.CharField(choices=[('Bedsitters', 'bedsitters'), ('Studio ', 'studio'), ('Bungalows', 'bungalows'), ('Rooms', 'rooms'), ('Single Rooms', 'single rooms'), ('Town Houses', 'town houses'), ('Flats and Apartments', 'flats and apartments'), ('Houses', 'houses'), ('Hostels', 'hostels')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='services',
            name='available',
            field=models.CharField(choices=[('NO', 'no'), ('YES', 'yes')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='services',
            name='category',
            field=models.CharField(choices=[('Phone repair', 'phone repair'), ('Barber', 'barber'), ('Kibanda foods', 'kibanda foods'), ('Water point', 'water point'), ('Massage', 'massage'), ('Saloon', 'saloon'), ('Shoe repair', 'shoe repair'), ('Spa', 'spa'), ('Library', 'library')], max_length=1000),
        ),
    ]
