# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-26 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0004_auto_20190822_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='image1',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
        migrations.AddField(
            model_name='business',
            name='image2',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
        migrations.AddField(
            model_name='business',
            name='image3',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
        migrations.AddField(
            model_name='business',
            name='image4',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
        migrations.AddField(
            model_name='business',
            name='image5',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.CharField(choices=[('Supermarkets', 'supermarkets'), ('Restaurants ', 'restaurants'), ('Electric Hardware', 'electric hardware'), ('Construction Material Hardware', 'construction material hardware'), ('Bars', 'bars'), ('Foods', 'foods'), ('Botique', 'botique'), ('Bookshop', 'bookshop'), ('Hospitals', 'hospitals')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='housing',
            name='category',
            field=models.CharField(choices=[('Town Houses', 'town houses'), ('Rooms', 'rooms'), ('Studio ', 'studio'), ('Hostels', 'hostels'), ('Single Rooms', 'single rooms'), ('Bedsitters', 'bedsitters'), ('Bungalows', 'bungalows'), ('Flats and Apartments', 'flats and apartments'), ('Houses', 'houses')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='services',
            name='category',
            field=models.CharField(choices=[('Water point', 'water point'), ('Saloon', 'saloon'), ('Kibanda foods', 'kibanda foods'), ('Phone repair', 'phone repair'), ('Shoe repair', 'shoe repair'), ('Library', 'library'), ('Massage', 'massage'), ('Spa', 'spa'), ('Barber', 'barber')], max_length=1000),
        ),
    ]
