# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-26 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0005_auto_20190826_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='image6',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
        migrations.AddField(
            model_name='housing',
            name='image1',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
        migrations.AddField(
            model_name='housing',
            name='image2',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
        migrations.AddField(
            model_name='housing',
            name='image3',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
        migrations.AddField(
            model_name='housing',
            name='image4',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
        migrations.AddField(
            model_name='housing',
            name='image5',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
        migrations.AddField(
            model_name='housing',
            name='image6',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
        migrations.AddField(
            model_name='services',
            name='image1',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
        migrations.AddField(
            model_name='services',
            name='image2',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
        migrations.AddField(
            model_name='services',
            name='image3',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
        migrations.AddField(
            model_name='services',
            name='image4',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
        migrations.AddField(
            model_name='services',
            name='image5',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
        migrations.AddField(
            model_name='services',
            name='image6',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.CharField(choices=[('Hospitals', 'hospitals'), ('Construction Material Hardware', 'construction material hardware'), ('Botique', 'botique'), ('Bookshop', 'bookshop'), ('Supermarkets', 'supermarkets'), ('Restaurants ', 'restaurants'), ('Bars', 'bars'), ('Foods', 'foods'), ('Electric Hardware', 'electric hardware')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='housing',
            name='category',
            field=models.CharField(choices=[('Studio ', 'studio'), ('Single Rooms', 'single rooms'), ('Bedsitters', 'bedsitters'), ('Bungalows', 'bungalows'), ('Town Houses', 'town houses'), ('Rooms', 'rooms'), ('Hostels', 'hostels'), ('Houses', 'houses'), ('Flats and Apartments', 'flats and apartments')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='services',
            name='available',
            field=models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='services',
            name='category',
            field=models.CharField(choices=[('Water point', 'water point'), ('Massage', 'massage'), ('Shoe repair', 'shoe repair'), ('Phone repair', 'phone repair'), ('Library', 'library'), ('Kibanda foods', 'kibanda foods'), ('Spa', 'spa'), ('Saloon', 'saloon'), ('Barber', 'barber')], max_length=1000),
        ),
    ]
