# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-26 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0006_auto_20190826_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='services',
            name='image6',
        ),
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.CharField(choices=[('Foods', 'foods'), ('Bookshop', 'bookshop'), ('Hospitals', 'hospitals'), ('Restaurants ', 'restaurants'), ('Bars', 'bars'), ('Electric Hardware', 'electric hardware'), ('Supermarkets', 'supermarkets'), ('Construction Material Hardware', 'construction material hardware'), ('Botique', 'botique')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='housing',
            name='category',
            field=models.CharField(choices=[('Bedsitters', 'bedsitters'), ('Houses', 'houses'), ('Studio ', 'studio'), ('Town Houses', 'town houses'), ('Hostels', 'hostels'), ('Single Rooms', 'single rooms'), ('Bungalows', 'bungalows'), ('Rooms', 'rooms'), ('Flats and Apartments', 'flats and apartments')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='services',
            name='available',
            field=models.CharField(choices=[('NO', 'no'), ('YES', 'yes')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='services',
            name='category',
            field=models.CharField(choices=[('Spa', 'spa'), ('Library', 'library'), ('Water point', 'water point'), ('Massage', 'massage'), ('Shoe repair', 'shoe repair'), ('Saloon', 'saloon'), ('Kibanda foods', 'kibanda foods'), ('Phone repair', 'phone repair'), ('Barber', 'barber')], max_length=1000),
        ),
    ]
