# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-27 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0007_auto_20190826_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.CharField(choices=[('Supermarkets', 'supermarkets'), ('Bookshop', 'bookshop'), ('Bars', 'bars'), ('Hospitals', 'hospitals'), ('Electric Hardware', 'electric hardware'), ('Botique', 'botique'), ('Restaurants ', 'restaurants'), ('Foods', 'foods'), ('Construction Material Hardware', 'construction material hardware')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='housing',
            name='category',
            field=models.CharField(choices=[('Flats and Apartments', 'flats and apartments'), ('Town Houses', 'town houses'), ('Bungalows', 'bungalows'), ('Hostels', 'hostels'), ('Studio ', 'studio'), ('Bedsitters', 'bedsitters'), ('Rooms', 'rooms'), ('Houses', 'houses'), ('Single Rooms', 'single rooms')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='services',
            name='category',
            field=models.CharField(choices=[('Massage', 'massage'), ('Barber', 'barber'), ('Spa', 'spa'), ('Shoe repair', 'shoe repair'), ('Library', 'library'), ('Kibanda foods', 'kibanda foods'), ('Phone repair', 'phone repair'), ('Saloon', 'saloon'), ('Water point', 'water point')], max_length=1000),
        ),
    ]
